### ISSUE TITLE
RHEL 8 fails to find appropriate GLIBC in /lib64

### ISSUE THREAD

**Issue by MarkUoLeeds** [isambard-sc/clifton#35]
hello, not sure if htis right place to report and ask for help...
(base) [earmgr@uol-lap-595680 ~]$ clifton-linux-x86_64 auth
clifton-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by clifton-linux-x86_64)
clifton-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by clifton-linux-x86_64)
clifton-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by clifton-linux-x86_64)
clifton-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by clifton-linux-x86_64)

it seems my laptop stops at GLIBC_2.28 when I use:
    ` strings /lib64/libc.so.6| grep -wi ^glibc_2...| sort -n`

maybe with Spack I could give it a friendly environment?

**Comment by milliams** [comment]
I am planning on releasing the next version of Clifton with binaries built against [musl](https://musl.libc.org/) which should allow it to run on any Linux system.

**Comment by obrookes** [comment]
Hi @milliams - sounds great! Any idea when that release might be?

**Comment by milliams** [comment]
I've just made the release at https://github.com/isambard-sc/clifton/releases/tag/0.1.3 let me know if there's any issues. You should try the `clifton-linux-musl-x86_64` binary.

**Comment by obrookes** [comment]
Works for me :)

**Comment by MarkUoLeeds** [comment]
Hello the binary runs, I will try follow the getting started steps 5 onwards, soon.


Dr. Mark Richardson
Technical Head of CEMAC ( www cemac ac uk )
Room 9.145b Earth and Environment Building
School of Earth and Environment
University of Leeds
LS2 9JT



________________________________
